version: "3.5"
services:
  main_website:
    image: aruanoguate/landivar_aws_project:photo_gallery
    container_name: photo_gallery
    environment:
      - MYSQLPASSWORD
    ports:
      - "80:5000" # DEV ONLY - The port 80 is exposed to the host
    networks:
      - net_001
networks:
  net_001:
      